/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShootManagerRouteImport } from './routes/shoot-manager'
import { Route as ShootDetailsRouteImport } from './routes/shoot-details'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CustomerSignupRouteImport } from './routes/customer-signup'
import { Route as CustomerProfileRouteImport } from './routes/customer-profile'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as CustomerHistoryRouteImport } from './routes/customer-history'
import { Route as CustomerGalleryRouteImport } from './routes/customer-gallery'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShootEditorRouteImport } from './routes/admin.shoot-editor'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootManagerRoute = ShootManagerRouteImport.update({
  id: '/shoot-manager',
  path: '/shoot-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDetailsRoute = ShootDetailsRouteImport.update({
  id: '/shoot-details',
  path: '/shoot-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer-signup',
  path: '/customer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer-profile',
  path: '/customer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer-login',
  path: '/customer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/customer-history',
  path: '/customer-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerGalleryRoute = CustomerGalleryRouteImport.update({
  id: '/customer-gallery',
  path: '/customer-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShootEditorRoute = AdminShootEditorRouteImport.update({
  id: '/shoot-editor',
  path: '/shoot-editor',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/packages'
    | '/profile'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/admin/shoot-editor'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/packages'
    | '/profile'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/admin/shoot-editor'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/packages'
    | '/profile'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/admin/shoot-editor'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerGalleryRoute: typeof CustomerGalleryRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  ProfileRoute: typeof ProfileRoute
  ShootDetailsRoute: typeof ShootDetailsRoute
  ShootManagerRoute: typeof ShootManagerRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-manager': {
      id: '/shoot-manager'
      path: '/shoot-manager'
      fullPath: '/shoot-manager'
      preLoaderRoute: typeof ShootManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-details': {
      id: '/shoot-details'
      path: '/shoot-details'
      fullPath: '/shoot-details'
      preLoaderRoute: typeof ShootDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-signup': {
      id: '/customer-signup'
      path: '/customer-signup'
      fullPath: '/customer-signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-profile': {
      id: '/customer-profile'
      path: '/customer-profile'
      fullPath: '/customer-profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-login': {
      id: '/customer-login'
      path: '/customer-login'
      fullPath: '/customer-login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-history': {
      id: '/customer-history'
      path: '/customer-history'
      fullPath: '/customer-history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-gallery': {
      id: '/customer-gallery'
      path: '/customer-gallery'
      fullPath: '/customer-gallery'
      preLoaderRoute: typeof CustomerGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shoot-editor': {
      id: '/admin/shoot-editor'
      path: '/shoot-editor'
      fullPath: '/admin/shoot-editor'
      preLoaderRoute: typeof AdminShootEditorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminShootEditorRoute: typeof AdminShootEditorRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShootEditorRoute: AdminShootEditorRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingConfirmedRoute: BookingConfirmedRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerGalleryRoute: CustomerGalleryRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  ProfileRoute: ProfileRoute,
  ShootDetailsRoute: ShootDetailsRoute,
  ShootManagerRoute: ShootManagerRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
