/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CustomerSignupRouteImport } from './routes/customer-signup'
import { Route as CustomerProfileRouteImport } from './routes/customer-profile'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as CustomerHistoryRouteImport } from './routes/customer-history'
import { Route as CustomerGalleryRouteImport } from './routes/customer-gallery'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer-signup',
  path: '/customer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer-profile',
  path: '/customer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer-login',
  path: '/customer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/customer-history',
  path: '/customer-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerGalleryRoute = CustomerGalleryRouteImport.update({
  id: '/customer-gallery',
  path: '/customer-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/gallery'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerGalleryRoute: typeof CustomerGalleryRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-signup': {
      id: '/customer-signup'
      path: '/customer-signup'
      fullPath: '/customer-signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-profile': {
      id: '/customer-profile'
      path: '/customer-profile'
      fullPath: '/customer-profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-login': {
      id: '/customer-login'
      path: '/customer-login'
      fullPath: '/customer-login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-history': {
      id: '/customer-history'
      path: '/customer-history'
      fullPath: '/customer-history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-gallery': {
      id: '/customer-gallery'
      path: '/customer-gallery'
      fullPath: '/customer-gallery'
      preLoaderRoute: typeof CustomerGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerGalleryRoute: CustomerGalleryRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
