/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyBookingRouteImport } from './routes/verify-booking'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShootManagerRouteImport } from './routes/shoot-manager'
import { Route as ShootDetailsRouteImport } from './routes/shoot-details'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PackageEditorRouteImport } from './routes/package-editor'
import { Route as MediaManagerRouteImport } from './routes/media-manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomestayEditorRouteImport } from './routes/homestay-editor'
import { Route as HomestayRouteImport } from './routes/homestay'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HeroEditorRouteImport } from './routes/hero-editor'
import { Route as GalleryEditorRouteImport } from './routes/gallery-editor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EnquiryEditorRouteImport } from './routes/enquiry-editor'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as CustomerSignupRouteImport } from './routes/customer-signup'
import { Route as CustomerProfileRouteImport } from './routes/customer-profile'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as CustomerHistoryRouteImport } from './routes/customer-history'
import { Route as CustomerGalleryRouteImport } from './routes/customer-gallery'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as AdminEnquiriesRouteImport } from './routes/admin-enquiries'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShootEditorRouteImport } from './routes/admin.shoot-editor'

const VerifyBookingRoute = VerifyBookingRouteImport.update({
  id: '/verify-booking',
  path: '/verify-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootManagerRoute = ShootManagerRouteImport.update({
  id: '/shoot-manager',
  path: '/shoot-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootDetailsRoute = ShootDetailsRouteImport.update({
  id: '/shoot-details',
  path: '/shoot-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageEditorRoute = PackageEditorRouteImport.update({
  id: '/package-editor',
  path: '/package-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaManagerRoute = MediaManagerRouteImport.update({
  id: '/media-manager',
  path: '/media-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayEditorRoute = HomestayEditorRouteImport.update({
  id: '/homestay-editor',
  path: '/homestay-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayRoute = HomestayRouteImport.update({
  id: '/homestay',
  path: '/homestay',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroEditorRoute = HeroEditorRouteImport.update({
  id: '/hero-editor',
  path: '/hero-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryEditorRoute = GalleryEditorRouteImport.update({
  id: '/gallery-editor',
  path: '/gallery-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryEditorRoute = EnquiryEditorRouteImport.update({
  id: '/enquiry-editor',
  path: '/enquiry-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupRoute = CustomerSignupRouteImport.update({
  id: '/customer-signup',
  path: '/customer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer-profile',
  path: '/customer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer-login',
  path: '/customer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/customer-history',
  path: '/customer-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerGalleryRoute = CustomerGalleryRouteImport.update({
  id: '/customer-gallery',
  path: '/customer-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin-enquiries',
  path: '/admin-enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShootEditorRoute = AdminShootEditorRouteImport.update({
  id: '/shoot-editor',
  path: '/shoot-editor',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-enquiries': typeof AdminEnquiriesRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/enquiry': typeof EnquiryRoute
  '/enquiry-editor': typeof EnquiryEditorRoute
  '/gallery': typeof GalleryRoute
  '/gallery-editor': typeof GalleryEditorRoute
  '/hero-editor': typeof HeroEditorRoute
  '/history': typeof HistoryRoute
  '/homestay': typeof HomestayRoute
  '/homestay-editor': typeof HomestayEditorRoute
  '/login': typeof LoginRoute
  '/media-manager': typeof MediaManagerRoute
  '/package-editor': typeof PackageEditorRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/reserve': typeof ReserveRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/verify-booking': typeof VerifyBookingRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-enquiries': typeof AdminEnquiriesRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/enquiry': typeof EnquiryRoute
  '/enquiry-editor': typeof EnquiryEditorRoute
  '/gallery': typeof GalleryRoute
  '/gallery-editor': typeof GalleryEditorRoute
  '/hero-editor': typeof HeroEditorRoute
  '/history': typeof HistoryRoute
  '/homestay': typeof HomestayRoute
  '/homestay-editor': typeof HomestayEditorRoute
  '/login': typeof LoginRoute
  '/media-manager': typeof MediaManagerRoute
  '/package-editor': typeof PackageEditorRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/reserve': typeof ReserveRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/verify-booking': typeof VerifyBookingRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-enquiries': typeof AdminEnquiriesRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-gallery': typeof CustomerGalleryRoute
  '/customer-history': typeof CustomerHistoryRoute
  '/customer-login': typeof CustomerLoginRoute
  '/customer-profile': typeof CustomerProfileRoute
  '/customer-signup': typeof CustomerSignupRoute
  '/enquiry': typeof EnquiryRoute
  '/enquiry-editor': typeof EnquiryEditorRoute
  '/gallery': typeof GalleryRoute
  '/gallery-editor': typeof GalleryEditorRoute
  '/hero-editor': typeof HeroEditorRoute
  '/history': typeof HistoryRoute
  '/homestay': typeof HomestayRoute
  '/homestay-editor': typeof HomestayEditorRoute
  '/login': typeof LoginRoute
  '/media-manager': typeof MediaManagerRoute
  '/package-editor': typeof PackageEditorRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/reserve': typeof ReserveRoute
  '/shoot-details': typeof ShootDetailsRoute
  '/shoot-manager': typeof ShootManagerRoute
  '/signup': typeof SignupRoute
  '/verify-booking': typeof VerifyBookingRoute
  '/admin/shoot-editor': typeof AdminShootEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-enquiries'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/enquiry'
    | '/enquiry-editor'
    | '/gallery'
    | '/gallery-editor'
    | '/hero-editor'
    | '/history'
    | '/homestay'
    | '/homestay-editor'
    | '/login'
    | '/media-manager'
    | '/package-editor'
    | '/packages'
    | '/profile'
    | '/reserve'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/verify-booking'
    | '/admin/shoot-editor'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-enquiries'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/enquiry'
    | '/enquiry-editor'
    | '/gallery'
    | '/gallery-editor'
    | '/hero-editor'
    | '/history'
    | '/homestay'
    | '/homestay-editor'
    | '/login'
    | '/media-manager'
    | '/package-editor'
    | '/packages'
    | '/profile'
    | '/reserve'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/verify-booking'
    | '/admin/shoot-editor'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-enquiries'
    | '/booking-confirmed'
    | '/customer-dashboard'
    | '/customer-gallery'
    | '/customer-history'
    | '/customer-login'
    | '/customer-profile'
    | '/customer-signup'
    | '/enquiry'
    | '/enquiry-editor'
    | '/gallery'
    | '/gallery-editor'
    | '/hero-editor'
    | '/history'
    | '/homestay'
    | '/homestay-editor'
    | '/login'
    | '/media-manager'
    | '/package-editor'
    | '/packages'
    | '/profile'
    | '/reserve'
    | '/shoot-details'
    | '/shoot-manager'
    | '/signup'
    | '/verify-booking'
    | '/admin/shoot-editor'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerGalleryRoute: typeof CustomerGalleryRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSignupRoute: typeof CustomerSignupRoute
  EnquiryRoute: typeof EnquiryRoute
  EnquiryEditorRoute: typeof EnquiryEditorRoute
  GalleryRoute: typeof GalleryRoute
  GalleryEditorRoute: typeof GalleryEditorRoute
  HeroEditorRoute: typeof HeroEditorRoute
  HistoryRoute: typeof HistoryRoute
  HomestayRoute: typeof HomestayRoute
  HomestayEditorRoute: typeof HomestayEditorRoute
  LoginRoute: typeof LoginRoute
  MediaManagerRoute: typeof MediaManagerRoute
  PackageEditorRoute: typeof PackageEditorRoute
  PackagesRoute: typeof PackagesRoute
  ProfileRoute: typeof ProfileRoute
  ReserveRoute: typeof ReserveRoute
  ShootDetailsRoute: typeof ShootDetailsRoute
  ShootManagerRoute: typeof ShootManagerRoute
  SignupRoute: typeof SignupRoute
  VerifyBookingRoute: typeof VerifyBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-booking': {
      id: '/verify-booking'
      path: '/verify-booking'
      fullPath: '/verify-booking'
      preLoaderRoute: typeof VerifyBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-manager': {
      id: '/shoot-manager'
      path: '/shoot-manager'
      fullPath: '/shoot-manager'
      preLoaderRoute: typeof ShootManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoot-details': {
      id: '/shoot-details'
      path: '/shoot-details'
      fullPath: '/shoot-details'
      preLoaderRoute: typeof ShootDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-editor': {
      id: '/package-editor'
      path: '/package-editor'
      fullPath: '/package-editor'
      preLoaderRoute: typeof PackageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-manager': {
      id: '/media-manager'
      path: '/media-manager'
      fullPath: '/media-manager'
      preLoaderRoute: typeof MediaManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-editor': {
      id: '/homestay-editor'
      path: '/homestay-editor'
      fullPath: '/homestay-editor'
      preLoaderRoute: typeof HomestayEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay': {
      id: '/homestay'
      path: '/homestay'
      fullPath: '/homestay'
      preLoaderRoute: typeof HomestayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-editor': {
      id: '/hero-editor'
      path: '/hero-editor'
      fullPath: '/hero-editor'
      preLoaderRoute: typeof HeroEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-editor': {
      id: '/gallery-editor'
      path: '/gallery-editor'
      fullPath: '/gallery-editor'
      preLoaderRoute: typeof GalleryEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry-editor': {
      id: '/enquiry-editor'
      path: '/enquiry-editor'
      fullPath: '/enquiry-editor'
      preLoaderRoute: typeof EnquiryEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-signup': {
      id: '/customer-signup'
      path: '/customer-signup'
      fullPath: '/customer-signup'
      preLoaderRoute: typeof CustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-profile': {
      id: '/customer-profile'
      path: '/customer-profile'
      fullPath: '/customer-profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-login': {
      id: '/customer-login'
      path: '/customer-login'
      fullPath: '/customer-login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-history': {
      id: '/customer-history'
      path: '/customer-history'
      fullPath: '/customer-history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-gallery': {
      id: '/customer-gallery'
      path: '/customer-gallery'
      fullPath: '/customer-gallery'
      preLoaderRoute: typeof CustomerGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-enquiries': {
      id: '/admin-enquiries'
      path: '/admin-enquiries'
      fullPath: '/admin-enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shoot-editor': {
      id: '/admin/shoot-editor'
      path: '/shoot-editor'
      fullPath: '/admin/shoot-editor'
      preLoaderRoute: typeof AdminShootEditorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminShootEditorRoute: typeof AdminShootEditorRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShootEditorRoute: AdminShootEditorRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerGalleryRoute: CustomerGalleryRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSignupRoute: CustomerSignupRoute,
  EnquiryRoute: EnquiryRoute,
  EnquiryEditorRoute: EnquiryEditorRoute,
  GalleryRoute: GalleryRoute,
  GalleryEditorRoute: GalleryEditorRoute,
  HeroEditorRoute: HeroEditorRoute,
  HistoryRoute: HistoryRoute,
  HomestayRoute: HomestayRoute,
  HomestayEditorRoute: HomestayEditorRoute,
  LoginRoute: LoginRoute,
  MediaManagerRoute: MediaManagerRoute,
  PackageEditorRoute: PackageEditorRoute,
  PackagesRoute: PackagesRoute,
  ProfileRoute: ProfileRoute,
  ReserveRoute: ReserveRoute,
  ShootDetailsRoute: ShootDetailsRoute,
  ShootManagerRoute: ShootManagerRoute,
  SignupRoute: SignupRoute,
  VerifyBookingRoute: VerifyBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
